//Unidades Funcionales
export const MOSTRAR_UNIDADES_FUNCIONALES = "MOSTRAR_UNIDADES_FUNCIONALES";
export const MOSTRAR_UNIDAD_FUNCIONAL_TITULAR = "MOSTRAR_UNIDAD_FUNCIONAL_TITULAR";
export const MOSTRAR_UNIDAD_FUNCIONAL = "MOSTRAR_UNIDAD_FUNCIONAL";

//Locador
export const MOSTRAR_LOCADOR = "MOSTRAR_LOCADOR";


//Locatarios
export const AGREGAR_LOCATARIO_CONTRATO = "AGREGAR_LOCATARIO_CONTRATO";
export const MOSTRAR_LOCATARIO = "MOSTRAR_LOCATARIO";



//Contratos
export const AGREGAR_CONTRATO = "AGREGAR_CONTRATO";
export const MOSTRAR_CONTRATO = "MOSTRAR_CONTRATO";




